[profile.default]
src = "src"
out = "out"
libs = ["lib"]
solc_version = "0.8.26"
optimizer = true
optimizer_runs = 200
evm_version = "cancun"

[rpc_endpoints]
xlayer_testnet = "https://testrpc.xlayer.tech/terigon"
xlayer = "https://rpc.xlayer.tech/terigon"

[etherscan]
xlayer_testnet = { key = "${OKLINK_API_KEY}", url = "https://www.oklink.com/api/v5/explorer/contract/verify" }
